In [1]:
import pandas as pd

gdp = pd.read_csv(
    r"C:\Users\jacob\Desktop\Finscope-main\data\raw\gdp_per_capita_ppp.csv"
)

gdp_clean = gdp[[
    "REF_AREA_LABEL",
    "TIME_PERIOD",
    "OBS_VALUE"
]].copy()

gdp_clean.columns = [
    "Country",
    "Year",
    "GDP_Per_Capita_PPP"
]

gdp_clean.head()

              Country  Year  GDP_Per_Capita_PPP
0          Uzbekistan  1999         2521.839511
1             Vanuatu  1999         2083.928312
2       Venezuela, RB  1999        13623.184267
3             Vietnam  1999         2420.935000
4  West Bank and Gaza  1999         3052.456558

In [2]:
inflation = pd.read_csv(
    r"C:\Users\jacob\Desktop\Finscope-main\data\raw\inflation.csv",
    skiprows=4
)

inflation_long = inflation.melt(
    id_vars=["Country Name"],
    var_name="Year",
    value_name="Inflation"
)

inflation_long.rename(
    columns={"Country Name":"Country"},
    inplace=True
)

inflation_long.head()

                       Country          Year Inflation
0                        Aruba  Country Code       ABW
1  Africa Eastern and Southern  Country Code       AFE
2                  Afghanistan  Country Code       AFG
3   Africa Western and Central  Country Code       AFW
4                       Angola  Country Code       AGO

In [3]:
unemployment = pd.read_csv(
    r"C:\Users\jacob\Desktop\Finscope-main\data\raw\unemployment.csv",
    skiprows=4
)

unemployment_long = unemployment.melt(
    id_vars=["Country Name"],
    var_name="Year",
    value_name="Unemployment"
)

unemployment_long.rename(
    columns={"Country Name":"Country"},
    inplace=True
)

unemployment_long.head()

                       Country          Year Unemployment
0                        Aruba  Country Code          ABW
1  Africa Eastern and Southern  Country Code          AFE
2                  Afghanistan  Country Code          AFG
3   Africa Western and Central  Country Code          AFW
4                       Angola  Country Code          AGO

In [4]:
gdp_clean["Year"] = gdp_clean["Year"].astype(str)

inflation_long["Year"] = inflation_long["Year"].astype(str)

unemployment_long["Year"] = unemployment_long["Year"].astype(str)

In [5]:
merged = pd.merge(
    gdp_clean,
    inflation_long,
    on=["Country","Year"],
    how="inner"
)

merged = pd.merge(
    merged,
    unemployment_long,
    on=["Country","Year"],
    how="inner"
)

print(merged.shape)

merged.head()

(8067, 5)

              Country  Year  GDP_Per_Capita_PPP Inflation Unemployment
0          Uzbekistan  1999         2521.839511       NaN         13.3
1             Vanuatu  1999         2083.928312  1.998975         8.29
2       Venezuela, RB  1999        13623.184267       NaN        14.53
3  West Bank and Gaza  1999         3052.456558  5.544392       10.382
4         Yemen, Rep.  1999         2491.672571  8.660219        11.46

In [6]:
# Keep only years from 2010 onwards

merged["Year"] = pd.to_numeric(merged["Year"], errors="coerce")

merged = merged[
    (merged["Year"] >= 2010) &
    (merged["Year"] <= 2025)
]

print("Shape after year filter:", merged.shape)

merged.head()

Shape after year filter: (3501, 5)

,Country,Year,GDP_Per_Capita_PPP,Inflation,Unemployment
12,Zambia,2016,3313.351216,17.86973,5.244
13,Zimbabwe,2016,4275.449351,-1.54367,5.896
14,Arab World,2017,14473.336385,NaN,11.115202
15,Caribbean small states,2017,20762.536588,NaN,8.24674
16,Central Europe and the Baltics,2017,29977.339815,NaN,5.27719

In [7]:
merged = merged.reset_index(drop=True)

In [8]:
merged.head()

,Country,Year,GDP_Per_Capita_PPP,Inflation,Unemployment
0,Zambia,2016,3313.351216,17.86973,5.244
1,Zimbabwe,2016,4275.449351,-1.54367,5.896
2,Arab World,2017,14473.336385,NaN,11.115202
3,Caribbean small states,2017,20762.536588,NaN,8.24674
4,Central Europe and the Baltics,2017,29977.339815,NaN,5.27719

In [9]:
merged = merged[
    (merged["Year"] >= 2010) &
    (merged["Year"] <= 2025)
]

merged = merged.reset_index(drop=True)

print(merged.shape)
merged.head()

(3501, 5)

,Country,Year,GDP_Per_Capita_PPP,Inflation,Unemployment
0,Zambia,2016,3313.351216,17.86973,5.244
1,Zimbabwe,2016,4275.449351,-1.54367,5.896
2,Arab World,2017,14473.336385,NaN,11.115202
3,Caribbean small states,2017,20762.536588,NaN,8.24674
4,Central Europe and the Baltics,2017,29977.339815,NaN,5.27719

In [10]:
print(merged["Year"].min())
print(merged["Year"].max())

2010
2024

In [11]:
# Remove rows with missing values

merged = merged.dropna()

print("Shape after removing nulls:", merged.shape)

Shape after removing nulls: (2478, 5)

In [12]:
print(merged["Year"].min())
print(merged["Year"].max())

2010
2024

In [13]:
merged.to_csv(
    r"C:\Users\jacob\Desktop\Finscope-main\data\processed\financial_health_dataset.csv",
    index=False
)

print("Dataset saved successfully!")

Dataset saved successfully!